CONFIGURATION.md
Godeps/Godeps.json
README.md
config.go
main.go

update some descriptions for huawei cloud service broker.

update documents for service broker

---

README.md

add Apache 2.0 license information

add license information

---

rdsbroker/broker.go

add configurations for auth

---

pkg/config/cloudcredentials.go
pkg/services/dcs/bind.go
pkg/services/dcs/deprovision.go
pkg/services/dcs/provision.go
pkg/services/dcs/types.go
pkg/services/dcs/unbind.go
pkg/services/dcs/update.go
pkg/services/dcs/utils.go
pkg/services/rds/utils.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/urls.go

add dcs features:
* provision
* deprovision
* bind
* unbind
* update

add dcs features

---

pkg/database/database.go
pkg/database/instancedetails.go
pkg/database/upgrades.go
pkg/services/dcs/deprovision.go
pkg/services/dcs/provision.go
pkg/services/dms/deprovision.go
pkg/services/dms/provision.go
pkg/services/obs/deprovision.go
pkg/services/obs/provision.go
pkg/services/rds/deprovision.go
pkg/services/rds/provision.go

add instance details

---

pkg/database/binddetails.go
pkg/database/database.go
pkg/database/instancedetails.go
pkg/services/dcs/bind.go
pkg/services/dcs/deprovision.go
pkg/services/dcs/provision.go
pkg/services/dcs/unbind.go
pkg/services/dms/bind.go
pkg/services/dms/deprovision.go
pkg/services/dms/unbind.go
pkg/services/obs/bind.go
pkg/services/obs/deprovision.go
pkg/services/obs/unbind.go
pkg/services/rds/bind.go
pkg/services/rds/deprovision.go
pkg/services/rds/provision.go
pkg/services/rds/unbind.go

add bind details

---

pkg/broker/broker.go
pkg/models/operation.go
pkg/models/proxy.go
pkg/services/dcs/deprovision.go
pkg/services/dcs/lastoperation.go
pkg/services/dcs/provision.go
pkg/services/dcs/update.go
pkg/services/dms/deprovision.go
pkg/services/dms/lastoperation.go
pkg/services/dms/provision.go
pkg/services/dms/update.go
pkg/services/obs/deprovision.go
pkg/services/obs/lastoperation.go
pkg/services/obs/provision.go
pkg/services/obs/update.go
pkg/services/rds/deprovision.go
pkg/services/rds/lastoperation.go
pkg/services/rds/provision.go
pkg/services/rds/update.go

handle last operation

---

config.json
vendor/github.com/pivotal-cf/brokerapi/catalog.go

add pre parameters

---

CONFIGURATION.md
config.json
pkg/services/dcs/provision.go
pkg/services/dcs/update.go
pkg/services/dms/provision.go
pkg/services/obs/provision.go
pkg/services/rds/bind.go
pkg/services/rds/provision.go
pkg/services/rds/types.go
pkg/services/rds/update.go

* improve rds provision config
* improve rds update config
* improve rds bind config

improve rds config

---

CONFIGURATION.md
config.json
pkg/services/obs/provision.go
pkg/services/obs/types.go
pkg/services/obs/update.go

improve obs config

---

CONFIGURATION.md
config.json
pkg/services/dcs/utils.go
pkg/services/dms/provision.go
pkg/services/dms/types.go
pkg/services/dms/update.go
pkg/services/dms/utils.go
pkg/services/rds/utils.go

improve dms config

---

config.json
pkg/broker/broker.go
pkg/services/dms/instance/bind.go
pkg/services/dms/instance/deprovision.go
pkg/services/dms/instance/lastoperation.go
pkg/services/dms/instance/provision.go
pkg/services/dms/instance/types.go
pkg/services/dms/instance/unbind.go
pkg/services/dms/instance/update.go
pkg/services/dms/instance/utils.go
pkg/services/dms/queue/bind.go
pkg/services/dms/queue/deprovision.go
pkg/services/dms/queue/lastoperation.go
pkg/services/dms/queue/provision.go
pkg/services/dms/queue/types.go
pkg/services/dms/queue/unbind.go
pkg/services/dms/queue/update.go
pkg/services/dms/queue/utils.go

add rabbitmq feature

---

config.json
pkg/services/rds/bind.go
pkg/services/rds/provision.go
pkg/services/rds/utils.go

fix bugs in rds

---

config.json
pkg/services/obs/utils.go

fix bugs in obs

---

config.json
pkg/services/dcs/bind.go
pkg/services/dcs/provision.go
pkg/services/dcs/types.go
pkg/services/dcs/update.go
vendor/github.com/huaweicloud/golangsdk/openstack/client.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/requests.go
vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/results.go

fix bugs in dcs

---

config.json
pkg/services/dms/queue/bind.go
pkg/services/dms/queue/types.go
pkg/services/dms/queue/utils.go
vendor/github.com/huaweicloud/golangsdk/openstack/client.go
vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/groups/urls.go
vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/queues/results.go
vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/queues/urls.go

fix bugs in dms queue

---

pkg/broker/broker.go
pkg/database/database.go
pkg/database/operationdetails.go
pkg/models/operation.go
pkg/models/proxy.go
pkg/services/dcs/deprovision.go
pkg/services/dcs/lastoperation.go
pkg/services/dcs/provision.go
pkg/services/dcs/update.go
pkg/services/dms/instance/deprovision.go
pkg/services/dms/instance/lastoperation.go
pkg/services/dms/instance/provision.go
pkg/services/dms/instance/update.go
pkg/services/dms/queue/deprovision.go
pkg/services/dms/queue/lastoperation.go
pkg/services/dms/queue/provision.go
pkg/services/dms/queue/update.go
pkg/services/obs/deprovision.go
pkg/services/obs/lastoperation.go
pkg/services/obs/provision.go
pkg/services/obs/update.go
pkg/services/rds/deprovision.go
pkg/services/rds/lastoperation.go
pkg/services/rds/provision.go
pkg/services/rds/update.go

improve asyc operations

---

config.json
docs/configuration.md
docs/configuration/dcs-imdg.md
docs/configuration/dcs-memcached.md
docs/configuration/dcs-redis.md
docs/configuration/dms-kafka.md
docs/configuration/dms-rabbitmq.md
docs/configuration/dms-standard.md
docs/configuration/obs.md
docs/configuration/rds-hwsql.md
docs/configuration/rds-postgresql.md
docs/configuration/rds-sqlserver.md
docs/usage/dcs-imdg.md
docs/usage/dcs-memcached.md
docs/usage/dcs-redis.md
docs/usage/dms-activemq.md
docs/usage/dms-kafka.md
docs/usage/dms-rabbitmq.md
docs/usage/dms-standard.md
docs/usage/obs.md
docs/usage/rds-hwsql.md
docs/usage/rds-mysql.md
docs/usage/rds-postgresql.md
docs/usage/rds-sqlserver.md

add usage docs

---

config.json
pkg/services/rds/bind.go
pkg/services/rds/utils.go

verify bind information

---

pkg/services/dcs/provision.go
pkg/services/dms/instance/provision.go
pkg/services/dms/queue/provision.go
pkg/services/obs/provision.go
pkg/services/rds/provision.go

Related-Bug: theopenlab/openlab#75

Output provisionParameters.UnknownFields

---

pkg/services/dcs/update.go
pkg/services/dms/instance/update.go

Related-Bugs: theopenlab/openlab#75

Output update API error details

---

pkg/services/dcs/deprovision.go
pkg/services/dms/instance/deprovision.go
pkg/services/dms/queue/deprovision.go
pkg/services/rds/deprovision.go

Related-Bugs: theopenlab/openlab#75

Output delete API error details

---

pkg/services/dcs/lastoperation.go
pkg/services/dms/instance/lastoperation.go
pkg/services/rds/lastoperation.go

Don't query instance details from DB when query last deprovision operation

---

cce/README.md

oc is an openshift command ;-)

fix-cce-doc-typo
